name: hello

on:
  push:
    branches:
      - main

jobs:
  elevated-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run flow
        uses: ./
        with:
          flow-path: ./flows/hello.yml
